name: expRender
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8.5
  - pip
  - pytorch=1.9.1
  - torchvision=0.10.1
  - torchaudio=0.9.1
  - cudatoolkit=11.3
  - pip:
    - opencv-python==4.5.2.54
    - numpy==1.22.3
    - matplotlib==3.4.3
    - tqdm==4.56.2
    - trimesh==3.9.20
    - pillow==8.1.0 
    - scikit-image==0.18.1
    - pytorch3d==0.7.5