name: expRender
channels:
  - pytorch
  - pytorch3d
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - pytorch=1.10.1
  - torchvision=0.11.2
  - torchaudio=0.10.1
  - cudatoolkit=11.3
  - pytorch3d
  - pip:
    - opencv-python>=4.5.5.64
    - scikit-image==0.18.1
    - trimesh==3.9.20
    - open3d==0.17.0
    - numpy
    - matplotlib
    - tqdm
    - pillow
    - natsort